{
  "domain": "grocery_categories",
  "scope": "food_only",
  "version": "1.0",
  "total_categories": 42,
  "max_items_per_note_limit": 88,
  "categories": [
    { "id": 1, "name": "Fresh Beef", "examples": ["steak", "mince", "brisket"], "typical_motshelo_item": true },
    { "id": 2, "name": "Fresh Goat/Lamb", "examples": ["chops", "stew meat"], "typical_motshelo_item": true },
    { "id": 3, "name": "Fresh Pork", "examples": ["chops", "ribs", "belly"], "typical_motshelo_item": true },
    { "id": 4, "name": "Fresh Chicken", "examples": ["whole", "breast", "thighs", "drumsticks"], "typical_motshelo_item": true },
    { "id": 5, "name": "Processed Meats", "examples": ["sausages", "bacon", "polony", "cold cuts"], "typical_motshelo_item": false },
    { "id": 6, "name": "Offal", "examples": ["liver", "tripe", "trotters", "ox tongue"], "typical_motshelo_item": true },
    { "id": 7, "name": "Fresh Whole Fish", "examples": ["tilapia", "bream", "mackerel"], "typical_motshelo_item": false },
    { "id": 8, "name": "Frozen Fish/Seafood", "examples": ["fillets", "prawns", "crayfish"], "typical_motshelo_item": false },
    { "id": 9, "name": "Fresh Vegetables", "examples": ["cabbage", "spinach", "tomatoes", "onions"], "typical_motshelo_item": false },
    { "id": 10, "name": "Fresh Fruits", "examples": ["apples", "oranges", "bananas", "mangoes"], "typical_motshelo_item": false },
    { "id": 11, "name": "Dried Vegetables/Legumes", "examples": ["beans", "lentils", "dried peas"], "typical_motshelo_item": false },
    { "id": 12, "name": "Starchy Staples", "examples": ["potatoes", "sweet potatoes", "butternut"], "typical_motshelo_item": false },
    { "id": 13, "name": "Maize/Grains", "examples": ["cornmeal (pap)", "sorghum", "rice"], "typical_motshelo_item": true },
    { "id": 14, "name": "Bread & Bakery", "examples": ["loaves", "rolls", "buns", "morogo bread"], "typical_motshelo_item": false },
    { "id": 15, "name": "Breakfast Cereals", "examples": ["corn flakes", "oats", "muesli"], "typical_motshelo_item": false },
    { "id": 16, "name": "Pasta & Noodles", "examples": ["spaghetti", "macaroni", "instant noodles"], "typical_motshelo_item": false },
    { "id": 17, "name": "Cooking Oils", "examples": ["sunflower", "olive", "vegetable oil"], "typical_motshelo_item": true },
    { "id": 18, "name": "Dairy: Milk", "examples": ["fresh", "long-life", "condensed"], "typical_motshelo_item": true },
    { "id": 19, "name": "Dairy: Cultured", "examples": ["yogurt", "maas (sour milk)", "buttermilk"], "typical_motshelo_item": false },
    { "id": 20, "name": "Dairy: Cheese", "examples": ["cheddar", "gouda", "cream cheese"], "typical_motshelo_item": false },
    { "id": 21, "name": "Dairy: Butter & Margarine", "examples": ["butter", "margarine spreads"], "typical_motshelo_item": false },
    { "id": 22, "name": "Eggs", "examples": ["fresh eggs"], "typical_motshelo_item": true },
    { "id": 23, "name": "Sugar & Sweeteners", "examples": ["white", "brown", "sweeteners"], "typical_motshelo_item": true },
    { "id": 24, "name": "Salt & Basic Spices", "examples": ["salt", "pepper", "paprika", "curry powder"], "typical_motshelo_item": true },
    { "id": 25, "name": "Herbs & Specialty Spices", "examples": ["oregano", "thyme", "cumin", "cinnamon"], "typical_motshelo_item": false },
    { "id": 26, "name": "Stock & Broth", "examples": ["cubes", "liquid stock", "bone broth"], "typical_motshelo_item": false },
    { "id": 27, "name": "Sauces & Condiments", "examples": ["ketchup", "mayo", "mustard", "BBQ", "soy"], "typical_motshelo_item": false },
    { "id": 28, "name": "Canned Vegetables", "examples": ["baked beans", "corn", "peas", "tomatoes"], "typical_motshelo_item": true },
    { "id": 29, "name": "Canned Fish", "examples": ["tuna", "sardines", "pilchards"], "typical_motshelo_item": true },
    { "id": 30, "name": "Canned Meat", "examples": ["corned beef", "spam", "vienna sausages"], "typical_motshelo_item": true },
    { "id": 31, "name": "Canned Fruits", "examples": ["peaches", "pears", "fruit cocktail"], "typical_motshelo_item": false },
    { "id": 32, "name": "Pickled & Fermented", "examples": ["pickles", "olives", "sauerkraut", "kimchi"], "typical_motshelo_item": false },
    { "id": 33, "name": "Jams & Spreads", "examples": ["jam", "marmalade", "peanut butter", "honey"], "typical_motshelo_item": false },
    { "id": 34, "name": "Baking Essentials", "examples": ["flour", "baking powder", "yeast", "cocoa"], "typical_motshelo_item": true },
    { "id": 35, "name": "Snacks (Savory)", "examples": ["chips", "pretzels", "popcorn", "biltong"], "typical_motshelo_item": false },
    { "id": 36, "name": "Snacks (Sweet)", "examples": ["biscuits", "cookies", "chocolates", "candy"], "typical_motshelo_item": false },
    { "id": 37, "name": "Nuts & Seeds", "examples": ["peanuts", "almonds", "sunflower seeds"], "typical_motshelo_item": false },
    { "id": 38, "name": "Dried Fruit", "examples": ["raisins", "dates", "dried mango"], "typical_motshelo_item": false },
    { "id": 39, "name": "Beverages: Hot", "examples": ["tea", "coffee", "hot chocolate"], "typical_motshelo_item": true },
    { "id": 40, "name": "Beverages: Cold/Juice", "examples": ["soft drinks", "juice", "concentrate"], "typical_motshelo_item": false },
    { "id": 41, "name": "Water", "examples": ["bottled", "sparkling"], "typical_motshelo_item": true },
    { "id": 42, "name": "Baby & Toddler Food", "examples": ["formula", "purees", "teething biscuits"], "typical_motshelo_item": false }
  ],
  "notes": {
    "typical_motshelo_item": "Indicates items commonly purchased via Motshelo bulk-buy groups in Botswana",
    "max_items_per_note_limit": "Users cannot exceed 88 items per Note per KPI #7"
  }
}