{
  "app": "Namatose",
  "version": "3.0",
  "total_kpis": 500,
  "domains": [
    {
      "id": 1,
      "name": "SNIS Core Logic Engine",
      "kpis": [
        {"id": 1, "name": "Total Items Created", "description": "Lifetime count of all items across all Notes."},
        {"id": 2, "name": "Items per Note (Avg)", "description": "Average number of items inside a single Note."},
        {"id": 3, "name": "Notes per Sum (Avg)", "description": "Average number of Notes combined into a Sum decision."},
        {"id": 4, "name": "Note-to-Sum Conversion Rate", "description": "Percentage of Notes that are used in at least one Sum."},
        {"id": 5, "name": "Item Price Update Frequency (days)", "description": "How often an item's price is refreshed."},
        {"id": 6, "name": "Note Cloning Rate", "description": "How many times a Note is cloned by other users."},
        {"id": 7, "name": "Max Items per Note (History Cap Check)", "description": "Highest item count in a single Note; must stay ≤88."},
        {"id": 8, "name": "Audio-to-Item Accuracy (%)", "description": "Voice capture success rate (correct item & price)."},
        {"id": 9, "name": "Image-to-Item Verification Rate (%)", "description": "Price tag photos that pass verification."},
        {"id": 10, "name": "Top 50 'Summed' Items", "description": "Most frequently compared products in Botswana."},
        {"id": 11, "name": "Item Deletion Rate (%)", "description": "Items deleted due to bad data or discontinuation."},
        {"id": 12, "name": "Note Sharing Frequency (per user/week)", "description": "How often users share lists via WhatsApp, etc."},
        {"id": 13, "name": "Average Lifespan of a Note (days)", "description": "From creation to archival/deletion."},
        {"id": 14, "name": "Metadata Density (tags per item)", "description": "Average number of tags attached to an item."},
        {"id": 15, "name": "Note Categorization Accuracy (%)", "description": "Items correctly placed in Note buckets (auto vs manual)."},
        {"id": 16, "name": "Sum Recalculation Frequency (per user/month)", "description": "How often users adjust budgets within a Sum."},
        {"id": 17, "name": "Active Sums per User", "description": "Number of active decision comparisons per user."},
        {"id": 18, "name": "Item Type Distribution (%)", "description": "Breakdown: Image vs Audio vs HTML vs Manual text items."},
        {"id": 19, "name": "Budget Variance (Pula)", "description": "Average difference between Estimated Sum and Actual Spend."},
        {"id": 20, "name": "Search-to-Item Add Rate (%)", "description": "Searches that result in adding an item to a Note."},
        {"id": 21, "name": "Note 'Collaborator' Count (avg)", "description": "Average number of users editing a shared shopping list."},
        {"id": 22, "name": "Item Tag Diversity (unique tags)", "description": "Total distinct custom tags created by users."},
        {"id": 23, "name": "Note Archive-to-Delete Ratio", "description": "Archived Notes vs. permanently deleted."},
        {"id": 24, "name": "Sum View Duration (seconds)", "description": "Time spent analyzing the Bloomberg-style comparison view."},
        {"id": 25, "name": "Item 'Pivot' Rate (%)", "description": "Frequency of substituting one item for another in a Sum."},
        {"id": 26, "name": "High-Contrast Toggle Usage (%)", "description": "Accessibility feature engagement."},
        {"id": 27, "name": "'Text-Only' Mode Frequency (%)", "description": "Usage of minimalist low-data interface."},
        {"id": 28, "name": "Note 'Due Date' Compliance (%)", "description": "Shopping lists completed on or before due date."},
        {"id": 29, "name": "Item Price Variance (Pula)", "description": "Price difference for same item across different Notes."},
        {"id": 30, "name": "Sum 'Analytics' Engagement (clicks/user/month)", "description": "How often users check the KPI dashboard."}
      ]
    },
    {
      "id": 2,
      "name": "Grocery-Specific KPIs",
      "kpis": [
        {"id": 31, "name": "Top 20 Most Added Grocery Items", "description": "Frequency of non-meat grocery items added to Notes."},
        {"id": 32, "name": "Average Price per Litre of Milk (Pula)", "description": "Tracking dairy inflation."},
        {"id": 33, "name": "Average Price per Dozen Eggs (Pula)", "description": "Key protein affordability metric."},
        {"id": 34, "name": "Maize Meal (Pap) Price per 10kg (Pula)", "description": "Staple food cost index."},
        {"id": 35, "name": "Cooking Oil Price per 2L (Pula)", "description": "Essential commodity tracking."},
        {"id": 36, "name": "Bread Loaf Price (Pula)", "description": "Daily bread cost monitoring."},
        {"id": 37, "name": "Sugar Price per 5kg (Pula)", "description": "Basic sweetener cost."},
        {"id": 38, "name": "Rice Price per 5kg (Pula)", "description": "Staple grain cost."},
        {"id": 39, "name": "Fresh Vegetable Basket Cost (7 items)", "description": "Weighted average of cabbage, spinach, tomato, onion, carrot, beetroot, lettuce."},
        {"id": 40, "name": "Fresh Fruit Basket Cost (5 items)", "description": "Apple, banana, orange, mango, watermelon."},
        {"id": 41, "name": "Canned Fish Price per 400g (Pula)", "description": "Affordable protein source."},
        {"id": 42, "name": "Tea Bag Price per 100-pack (Pula)", "description": "Household hot beverage cost."},
        {"id": 43, "name": "Coffee Price per 250g (Pula)", "description": "Discretionary spending indicator."},
        {"id": 44, "name": "Soft Drink Price per 2L (Pula)", "description": "Non-essential beverage inflation."},
        {"id": 45, "name": "Baby Formula Price per 900g (Pula)", "description": "Vulnerable household cost."},
        {"id": 46, "name": "Diapers Price per pack (Pula)", "description": "Childcare cost indicator."},
        {"id": 47, "name": "Frozen Vegetable Popularity (units/month)", "description": "Demand for frozen vs fresh."},
        {"id": 48, "name": "Snack Category Share of Grocery Spend (%)", "description": "Biscuits, chips, sweets."},
        {"id": 49, "name": "Private Label vs Branded Item Ratio", "description": "Preference for store brands."},
        {"id": 50, "name": "Grocery Item Out-of-Stock Rate (%)", "description": "Items marked unavailable by users."},
        {"id": 51, "name": "Grocery Price Disparity Index (urban vs rural)", "description": "Ratio of Gaborone prices to village prices."},
        {"id": 52, "name": "Organic/Free-Range Tag Usage", "description": "Premium segment demand."},
        {"id": 53, "name": "Halal-Certified Item Adds", "description": "Religious compliance tracking."},
        {"id": 54, "name": "Imported vs Local Grocery Ratio", "description": "Support for local producers."},
        {"id": 55, "name": "Bulk-Buy Grocery Frequency", "description": "Multi-unit purchases per Note."},
        {"id": 56, "name": "Perishable Item Waste Reports (per month)", "description": "Items marked #Spoiled."},
        {"id": 57, "name": "Frozen Meat vs Fresh Meat Share (%)", "description": "Preference for frozen protein."},
        {"id": 58, "name": "Average Grocery List Size (items)", "description": "Typical household shopping trip."},
        {"id": 59, "name": "Grocery Savings via Comparison (Pula/user/month)", "description": "Money saved by choosing lowest price."},
        {"id": 60, "name": "Digital Receipt Upload Rate for Groceries", "description": "Users sharing till slips."}
      ]
    },
    {
      "id": 3,
      "name": "Meat-Specific KPIs (Cattle, Goat, Sheep, Pig, Chicken, Game)",
      "kpis": [
        {"id": 61, "name": "Total Animals 'Summed' (lifetime)", "description": "Count of cows, goats, pigs, etc. processed."},
        {"id": 62, "name": "Average Price per KG Beef (Pula)", "description": "Retail price benchmark."},
        {"id": 63, "name": "Average Price per KG Goat (Pula)", "description": "Ritual and event demand."},
        {"id": 64, "name": "Average Price per KG Pork (Pula)", "description": "Pork cut prices."},
        {"id": 65, "name": "Average Price per KG Chicken (Pula)", "description": "Poultry affordability."},
        {"id": 66, "name": "Average Price per KG Game (Pula)", "description": "Venison market."},
        {"id": 67, "name": "Carcass Weight Accuracy (%)", "description": "Estimated vs actual scale weight."},
        {"id": 68, "name": "Meat Grade Distribution (%)", "description": "A-grade vs C-grade listings."},
        {"id": 69, "name": "Breed Popularity (top 5)", "description": "e.g., Brahman, Nguni, Landrace."},
        {"id": 70, "name": "Slaughter-to-Delivery Time (hours)", "description": "Freshness metric."},
        {"id": 71, "name": "Distance from Farm to Consumer (km)", "description": "Supply chain efficiency."},
        {"id": 72, "name": "Meat Wastage Reports (kg/month)", "description": "#Spoiled or #Wasted tags."},
        {"id": 73, "name": "Distribution Mode Preference (Divide Equally vs Share Groups)", "description": "User choice ratio."},
        {"id": 74, "name": "Top 5 Abattoirs by Volume", "description": "Partner performance ranking."},
        {"id": 75, "name": "Cold Chain Integrity Reports (%)", "description": "#Cold vs #Warm tag frequency."},
        {"id": 76, "name": "Whole Animal vs Retail Cut Ratio", "description": "Bulk-buy behavior."},
        {"id": 77, "name": "Namatose vs Supermarket Meat Price Gap (%)", "description": "Competitive advantage."},
        {"id": 78, "name": "Active Abattoir Partners (count)", "description": "Logistics network breadth."},
        {"id": 79, "name": "Farmer Response Time (hours)", "description": "Time from interest to listing confirmation."},
        {"id": 80, "name": "Meat Delivery Success Rate (%)", "description": "Orders reaching members."},
        {"id": 81, "name": "Offal Set Popularity (units/month)", "description": "Liver, tripe, trotters, etc."},
        {"id": 82, "name": "Chicken Cuts Popularity Index", "description": "Thighs vs breasts vs wings."},
        {"id": 83, "name": "Bulk Grain Split Frequency (non-meat Motshelo)", "description": "Maize, sorghum, beans."},
        {"id": 84, "name": "Supplier Stock-Out Frequency (days/month)", "description": "Supply chain gaps."},
        {"id": 85, "name": "Local vs Imported Meat Ratio", "description": "Support for Botswana beef."},
        {"id": 86, "name": "Livestock Listing Frequency (per week)", "description": "Farmer engagement."},
        {"id": 87, "name": "Animal Summary Accuracy (%)", "description": "Errors in beast ID/breed listings."},
        {"id": 88, "name": "Seasonal Meat Demand Variance", "description": "Easter vs Independence vs Christmas."},
        {"id": 89, "name": "Halal Meat Tagging Rate (%)", "description": "Religious compliance."},
        {"id": 90, "name": "Average Weight of 'Small Shares' (kg)", "description": "Budget buyer habits."},
        {"id": 91, "name": "Supplier Payment Satisfaction (rating /5)", "description": "Farmer feedback."},
        {"id": 92, "name": "Regional Meat Scarcity Index (1-10)", "description": "Areas with low supply."},
        {"id": 93, "name": "Slot Reservation Speed (hours)", "description": "Time to fill a 10-slot animal."},
        {"id": 94, "name": "Popular Meat Cut by Region", "description": "e.g., Gaborone prefers steak, villages prefer stew cuts."},
        {"id": 95, "name": "Carcass Utilization Rate (%)", "description": "Percentage of animal sold (target 100%)."},
        {"id": 96, "name": "Biltong & Droëwors Sales Volume (kg/month)", "description": "Processed meat demand."},
        {"id": 97, "name": "Farmer Direct Listing Rate (%)", "description": "Listings without designer middleman."},
        {"id": 98, "name": "Meat Subscription (weekly box) Adoption", "description": "Recurring meat orders."},
        {"id": 99, "name": "Average Meat Spend per Motshelo Group (Pula/month)", "description": "Group protein budget."},
        {"id": 100, "name": "Meat Provenance Transparency Score (%)", "description": "Listings with farm-of-origin data."}
      ]
    },
    {
      "id": 4,
      "name": "Location & Geography KPIs (Region, Town, Area, Neighborhood)",
      "kpis": [
        {"id": 101, "name": "Gaborone vs Rural Usage Ratio", "description": "Urban/rural divide."},
        {"id": 102, "name": "Regional Price Disparity Index (by district)", "description": "Gaborone vs Francistown vs Maun vs Ghanzi vs Kasane."},
        {"id": 103, "name": "Top 10 Towns by Pula Saved (monthly)", "description": "Geographic impact leaderboard."},
        {"id": 104, "name": "Village-Level Adoption Rate (%)", "description": "Penetration in cattle-post areas."},
        {"id": 105, "name": "Regional Meat Preference (beef vs goat vs game)", "description": "Central (beef) vs Southern (goat)."},
        {"id": 106, "name": "Network Performance by Region (latency ms)", "description": "Mascom vs Orange vs BTC per district."},
        {"id": 107, "name": "Regional Logistics Success Rate (%)", "description": "On-time delivery by district."},
        {"id": 108, "name": "Motshelo Density (groups per 1000 people)", "description": "By town/neighbourhood."},
        {"id": 109, "name": "Impact on Local Butchery Foot Traffic (correlation)", "description": "App usage vs in-store sales."},
        {"id": 110, "name": "Digital Receipt Adoption by Region (%)", "description": "Moving away from paper."},
        {"id": 111, "name": "Setswana vs English Language Preference by Region", "description": "UI language setting ratio."},
        {"id": 112, "name": "Regional Contribution Consistency (on-time Motshelo payment %)", "description": "Which areas pay on time?"},
        {"id": 113, "name": "Ghanzi-Sourced Meat Volume (kg/month)", "description": "Tracking the 'Meat Capital'."},
        {"id": 114, "name": "Small-Holder Farmer Participation by District", "description": "Non-commercial farmers."},
        {"id": 115, "name": "Regional Price Transparency Score (1-10)", "description": "How much market data is public per region."},
        {"id": 116, "name": "Mobile Banking Uptime in Rural Areas (%)", "description": "Impact on transaction success."},
        {"id": 117, "name": "Regional Shared Transport Efficiency (kg per trip)", "description": "Grouping deliveries geographically."},
        {"id": 118, "name": "Urban Motshelo vs Traditional Motshelo Adoption Rate", "description": "Digital vs in-person group."},
        {"id": 119, "name": "Regional Market Gaps (high demand, low supplier count)", "description": "Opportunity heatmap."},
        {"id": 120, "name": "Neighbourhood-Level Item Availability Score", "description": "Which items are missing in which ward."},
        {"id": 121, "name": "Average Delivery Distance per Motshelo (km)", "description": "Farm to group."},
        {"id": 122, "name": "Township vs Suburb Spending Pattern", "description": "Molepolole vs Phakalane vs Gaborone CBD."},
        {"id": 123, "name": "Border Town Cross-Border Activity (e.g., Tlokweng, Ramotswa)", "description": "South Africa imports influence."},
        {"id": 124, "name": "Remote Area Dweller (RAD) Participation Rate", "description": "Inclusion of indigenous communities."},
        {"id": 125, "name": "Region with Fastest Motshelo Slot Fill Time", "description": "Demand heatmap."},
        {"id": 126, "name": "Regional Meat Spoilage Rate (%)", "description": "Cold chain failure by district."},
        {"id": 127, "name": "Neighbourhood Peer Trust Score (avg)", "description": "Cluster-level reliability."},
        {"id": 128, "name": "Town with Highest Average Sum Value (Pula)", "description": "Wealth indicator."},
        {"id": 129, "name": "Rural Offline Mode Usage (%)", "description": "Zero-data session reliance."},
        {"id": 130, "name": "New Motshelo Groups Created per Region (weekly)", "description": "Growth by geography."}
      ]
    },
    {
      "id": 5,
      "name": "Human Behaviour & Demographics (App-Crucial Only)",
      "kpis": [
        {"id": 131, "name": "User Gender Distribution (%)", "description": "Male/Female/Other – for financial inclusion targeting."},
        {"id": 132, "name": "Age Group Distribution (18-25, 26-35, 36-50, 50+)", "description": "Digital adoption by generation."},
        {"id": 133, "name": "Primary Language (Setswana vs English vs Other)", "description": "UI and support needs."},
        {"id": 134, "name": "Household Size (avg persons)", "description": "Impacts bulk buying."},
        {"id": 135, "name": "Employment Status (Employed, Self-employed, Unemployed, Retired)", "description": "Spending power."},
        {"id": 136, "name": "Monthly Income Bracket (distribution)", "description": "For LTV and affordability."},
        {"id": 137, "name": "Mobile Banking User Rate (%)", "description": "MyZaka, Orange Money, Smega."},
        {"id": 138, "name": "Smartphone Type (Android vs iOS vs Feature Phone)", "description": "Technical targeting."},
        {"id": 139, "name": "User Trust Score (derived from history)", "description": "Peer rating and transaction reliability."},
        {"id": 140, "name": "Motshelo Role Distribution (Member, Group Head A, Group Head B)", "description": "Leadership ratio."},
        {"id": 141, "name": "Female-Led Motshelo Rate (%)", "description": "Women's economic empowerment."},
        {"id": 142, "name": "Digital Literacy Score (based on feature usage)", "description": "Low vs high engagement."},
        {"id": 143, "name": "Referral Behaviour (average invites sent)", "description": "Viral coefficient by demographic."},
        {"id": 144, "name": "Risk Aversion Index (prefers fixed shares vs variable)", "description": "User personality."},
        {"id": 145, "name": "Community Leadership Tenure (months)", "description": "Manager stability."},
        {"id": 146, "name": "Peer-to-Peer Lending Participation Rate (%)", "description": "Social fund usage."},
        {"id": 147, "name": "Frequency of 'Meat Votes' (VoteWonda)", "description": "Democratic engagement."},
        {"id": 148, "name": "Conflict Resolution Style (arbitration vs auto-split)", "description": "User preference."},
        {"id": 149, "name": "Price Sensitivity Score (switches items often)", "description": "Bargain hunter vs loyalist."},
        {"id": 150, "name": "Bulk Buyer vs Small Share Buyer Ratio", "description": "Consumer segmentation."},
        {"id": 151, "name": "User Sentiment Polarity (positive/negative)", "description": "From PulseUpdater logs."},
        {"id": 152, "name": "Churn Risk Score (1-10)", "description": "Predictive retention model."},
        {"id": 153, "name": "Offline-First User Percentage", "description": "Relies on sync later."},
        {"id": 154, "name": "Peak Shopping Hour by Demographic (e.g., working moms vs students)", "description": "Engagement timing."},
        {"id": 155, "name": "Social Sharing Frequency by Age Group", "description": "Younger users share more."},
        {"id": 156, "name": "Trust in Algorithm (accepts auto-split vs manual adjust)", "description": "Botho principle metric."},
        {"id": 157, "name": "New Feature Adoption Curve (early adopter %)", "description": "Demographic of innovators."},
        {"id": 158, "name": "User-Reported Fairness Score (1-5)", "description": "Perceived equity in group splits."},
        {"id": 159, "name": "Intergenerational Usage (parent-child joint accounts)", "description": "Family units."},
        {"id": 160, "name": "User's Primary Shopping Motivation (savings vs convenience vs quality)", "description": "Psychographic."}
      ]
    },
    {
      "id": 6,
      "name": "Economic Value, Commissions & Financial Partners (Banks & Mobile Money)",
      "kpis": [
        {"id": 161, "name": "Total Transaction Volume (TTV) – Pula", "description": "Gross flow."},
        {"id": 162, "name": "Average Transaction Value (ATV) – Pula", "description": "Per Motshelo or list."},
        {"id": 163, "name": "Namatose Commission Revenue (0.5% base) – Pula", "description": "Platform income."},
        {"id": 164, "name": "Designer Cut Total (Pula paid to Sourcers)", "description": "Curator earnings."},
        {"id": 165, "name": "Designer Earnings per Note (Pula)", "description": "Profitability of listings."},
        {"id": 166, "name": "Commission-to-TTV Ratio (%)", "description": "Platform yield."},
        {"id": 167, "name": "Payment Success Rate (%)", "description": "Overall across all providers."},
        {"id": 168, "name": "Average Savings % per Member vs Retail", "description": "Group impact."},
        {"id": 169, "name": "Tag Purchase Revenue (Pula/month)", "description": "Business visibility income."},
        {"id": 170, "name": "Daily Gross Revenue (DGR) – Pula", "description": "Daily income."},
        {"id": 171, "name": "Revenue per Active Note (Pula)", "description": "Monetisation efficiency."},
        {"id": 172, "name": "Cost of Acquisition (CAC) – Pula", "description": "Marketing spend per active user."},
        {"id": 173, "name": "User Lifetime Value (LTV) – Pula", "description": "Long-term revenue."},
        {"id": 174, "name": "Wallet Withdrawal Frequency (per designer/month)", "description": "Cash-out behaviour."},
        {"id": 175, "name": "Failed Payment Recovery Rate (%)", "description": "Retry success."},
        {"id": 176, "name": "Average 'Manager Fee' (Pula per group/month)", "description": "Motshelo head labor cost."},
        {"id": 177, "name": "Total 'Social Fund' Balance (Pula)", "description": "Community safety net."},
        {"id": 178, "name": "Borrow Request Approval Rate (%)", "description": "P2P lending liquidity."},
        {"id": 179, "name": "Average Loan Repayment Time (days)", "description": "Debt clearing speed."},
        {"id": 180, "name": "Delinquency Rate (% unpaid contributions)", "description": "Bad debt."},
        {"id": 181, "name": "Financial Transparency Score (1-10)", "description": "User trust in Sum calculations."},
        {"id": 182, "name": "Total 'Pula Saved' Community-Wide", "description": "Impact for investors."},
        {"id": 183, "name": "Average Fee per User (Pula/month)", "description": "Platform cost per user."},
        {"id": 184, "name": "Designer Retention Rate (% after 3 months)", "description": "Curator loyalty."},
        {"id": 185, "name": "Transaction Velocity (days from Sum creation to payment)", "description": "Efficiency."},
        {"id": 186, "name": "In-App Ad Click-Through (Tags) (%)", "description": "Paid tag performance."},
        {"id": 187, "name": "Referral Reward Payouts (Pula/month)", "description": "Organic growth cost."},
        {"id": 188, "name": "Financial Error Rate (disputes per 1000 transactions)", "description": "Sum calc disputes."},
        {"id": 189, "name": "Percentage of Users with Linked Wallets (%)", "description": "Financial inclusion."},
        {"id": 190, "name": "Commission Payout Speed (hours from transaction to designer)", "description": "Trust metric."},
        {"id": 191, "name": "Payment Success Rate by Mobile Money Provider (%)", "description": "Mascom MyZaka vs Orange Money vs BTC Smega."},
        {"id": 192, "name": "Payment Success Rate by Bank (each bank)", "description": "FNB, Stanchart, Stanbic, BSB, NDB, BBS, Access, Bank Gaborone, FCB, Absa."},
        {"id": 193, "name": "Mobile Money Market Share on Namatose (%)", "description": "MyZaka, Orange Money, Smega distribution."},
        {"id": 194, "name": "Bank Transfer Adoption Rate (%)", "description": "Users preferring bank vs mobile money."},
        {"id": 195, "name": "Average Transaction Value by Provider (Pula)", "description": "Which provider handles larger sums."},
        {"id": 196, "name": "Designer Payout Method Preference (bank vs mobile money)", "description": "Curator withdrawal choice."},
        {"id": 197, "name": "MyZaka Transaction Volume (Pula/month)", "description": "Mascom's share."},
        {"id": 198, "name": "Orange Money Transaction Volume (Pula/month)", "description": "Orange's share."},
        {"id": 199, "name": "BTC Smega Transaction Volume (Pula/month)", "description": "BTC's share."},
        {"id": 200, "name": "FNB Linked Wallet Penetration (%)", "description": "Users with FNB account linked."},
        {"id": 201, "name": "Stanchart (SCB) Linked Wallet Penetration (%)", "description": "Standard Chartered users."},
        {"id": 202, "name": "Stanbic (SBB) Linked Wallet Penetration (%)", "description": "Stanbic users."},
        {"id": 203, "name": "BSB Linked Wallet Penetration (%)", "description": "Botswana Savings Bank users."},
        {"id": 204, "name": "NDB Linked Wallet Penetration (%)", "description": "National Development Bank users."},
        {"id": 205, "name": "BBS Linked Wallet Penetration (%)", "description": "BBS Bank users."},
        {"id": 206, "name": "Access Bank Linked Wallet Penetration (%)", "description": "Access Bank Botswana users."},
        {"id": 207, "name": "Bank Gaborone (BG) Linked Wallet Penetration (%)", "description": "Bank Gaborone users."},
        {"id": 208, "name": "FCB Linked Wallet Penetration (%)", "description": "First Capital Bank users."},
        {"id": 209, "name": "Absa Linked Wallet Penetration (%)", "description": "Absa (formerly Barclays) users."},
        {"id": 210, "name": "Bank of Botswana (BoB) Regulatory Reporting Compliance (%)", "description": "Central bank data submissions."},
        {"id": 211, "name": "Mobile Money Transaction Failure Rate by Region", "description": "Rural vs urban."},
        {"id": 212, "name": "Bank Transfer Speed (hours from initiation to settlement)", "description": "Average clearing time."},
        {"id": 213, "name": "Mobile Money Float Replenishment Frequency", "description": "Operational liquidity."},
        {"id": 214, "name": "User Preference for Cash vs Digital (%)", "description": "Still using cash outside app."},
        {"id": 215, "name": "Motshelo Group Bank Account Linking Rate", "description": "Groups with shared corporate account."},
        {"id": 216, "name": "Micro-loan Origination via Mobile Money (%)", "description": "Social fund disbursement channel."},
        {"id": 217, "name": "Cross-Border Payment Attempts (South Africa)", "description": "Tlokweng/Ramotswa border activity."},
        {"id": 218, "name": "Financial Inclusion Lift (new wallet registrations attributed to Namatose)", "description": "First-time digital wallet users."},
        {"id": 219, "name": "Average Mobile Money Balance Held by Users (Pula)", "description": "Liquidity available for Motshelo."},
        {"id": 220, "name": "Bank API Uptime for Balance Checks (%)", "description": "Partner reliability."}
      ]
    },
    {
      "id": 7,
      "name": "Community & Motshelo Health",
      "kpis": [
        {"id": 221, "name": "Total Active Motshelo Groups", "description": "Micro-communities count."},
        {"id": 222, "name": "Average Motshelo Group Size (members)", "description": "Social fabric density."},
        {"id": 223, "name": "New Member Invite Success Rate (%)", "description": "Virality of group structure."},
        {"id": 224, "name": "Quorum Achievement Rate (4+ confirmations) (%)", "description": "Decision readiness."},
        {"id": 225, "name": "Voter Participation Rate (%)", "description": "Engagement in 'Meat Votes'."},
        {"id": 226, "name": "Consensus Time (hours to agree on a cow)", "description": "Group decisiveness."},
        {"id": 227, "name": "Member Churn per Group (% per month)", "description": "Stability."},
        {"id": 228, "name": "Manager-to-Member Ratio", "description": "Identify overworked leaders."},
        {"id": 229, "name": "Total 'Bereavement Logic' Payouts (Pula)", "description": "Social impact during grief."},
        {"id": 230, "name": "Private vs Public Groups Ratio", "description": "Privacy preference."},
        {"id": 231, "name": "Group 'Health' Score (interaction frequency)", "description": "Composite metric."},
        {"id": 232, "name": "Conflict Resolution Time (days)", "description": "Dispute efficiency."},
        {"id": 233, "name": "Peer Trust Score Average (1-5)", "description": "Member reliability."},
        {"id": 234, "name": "Manager Role Handover Frequency (per group/year)", "description": "Succession planning."},
        {"id": 235, "name": "Social Sharing Frequency (Sums to WhatsApp)", "description": "Off-app virality."},
        {"id": 236, "name": "Motshelo Savings Goal Achievement Rate (%)", "description": "Long-term success."},
        {"id": 237, "name": "Group 'Expansion' Rate (new slots added per month)", "description": "Growth."},
        {"id": 238, "name": "Inactive Member Purge Rate (per month)", "description": "Data cleanliness."},
        {"id": 239, "name": "Cross-Group Membership (users in >1 Motshelo)", "description": "Super-connectors."},
        {"id": 240, "name": "Average 'Age' of a Motshelo Group (months)", "description": "Stability."},
        {"id": 241, "name": "Community Poll (VoteWonda) Participation (%)", "description": "Engagement."},
        {"id": 242, "name": "Member 'Fairness' Rating (qualitative 1-5)", "description": "Satisfaction with splits."},
        {"id": 243, "name": "New Group Creation Velocity (per week)", "description": "Growth rate."},
        {"id": 244, "name": "Validated Meat Quality Reports (per month)", "description": "'High Quality' tags."},
        {"id": 245, "name": "Peer Assistance Frequency (covers others' costs)", "description": "Altruism."},
        {"id": 246, "name": "Moderator Activity Level (actions per week)", "description": "PermissionsManager usage."},
        {"id": 247, "name": "Group Goal Achievement Speed (days vs target)", "description": "Efficiency."},
        {"id": 248, "name": "Neighbourhood Adoption Rate (groups per ward)", "description": "Local penetration."},
        {"id": 249, "name": "Motshelo 'Festive Season' Spike (Dec multiplier)", "description": "Seasonal surge."},
        {"id": 250, "name": "Community 'Knowledge' Sharing (price tips per user)", "description": "Collaborative behaviour."}
      ]
    },
    {
      "id": 8,
      "name": "Technical Performance & Offline UX",
      "kpis": [
        {"id": 251, "name": "Sync Success Rate (%)", "description": "Offline events correctly updated."},
        {"id": 252, "name": "Average Sync Latency (seconds)", "description": "Time in un-synced state."},
        {"id": 253, "name": "Local Storage Usage per User (MB)", "description": "Browser limit management (5MB)."},
        {"id": 254, "name": "Page Load Time (seconds)", "description": "Single Page Illusion performance."},
        {"id": 255, "name": "Cache Hit Ratio (%)", "description": "Assets loaded locally."},
        {"id": 256, "name": "Audio Capture Success Rate (%)", "description": "Voice recording failures."},
        {"id": 257, "name": "Image Compression Efficiency (ratio)", "description": "Quality vs size."},
        {"id": 258, "name": "Crash-Free Session Rate (%)", "description": "Stability."},
        {"id": 259, "name": "Battery Drain per Session (% per hour)", "description": "Optimisation."},
        {"id": 260, "name": "Data Consumption per Active Session (MB)", "description": "Data-First design success."},
        {"id": 261, "name": "Offline 'Queue' Depth (pending events)", "description": "Backlog waiting for signal."},
        {"id": 262, "name": "Conflict Resolution Success (%)", "description": "Multi-user edit reconciliation."},
        {"id": 263, "name": "App Update Adoption Speed (days to 80%)", "description": "Version migration."},
        {"id": 264, "name": "Notification Delivery Success (%)", "description": "Push/WhatsApp reliability."},
        {"id": 265, "name": "Deep-Link Success Rate (%)", "description": "WhatsApp-to-app navigation."},
        {"id": 266, "name": "Font Rendering Speed (ms)", "description": "Sora/Space Mono performance."},
        {"id": 267, "name": "Memory Leak Detection (sessions >30min)", "description": "Long-session stability."},
        {"id": 268, "name": "Biometric/PIN Login Speed (ms)", "description": "Entry friction."},
        {"id": 269, "name": "Javascript 'Pulse' Logging Overhead (ms)", "description": "Analytics performance impact."},
        {"id": 270, "name": "Asset Lazy-Loading Performance (images/sec)", "description": "Rendering speed in lists."},
        {"id": 271, "name": "Smoothness (FPS avg)", "description": "Scrolling performance."},
        {"id": 272, "name": "Error Log Frequency (per 1000 sessions)", "description": "Client-side errors."},
        {"id": 273, "name": "PWA 'Add to Home Screen' Rate (%)", "description": "User commitment."},
        {"id": 274, "name": "Cross-Browser Compatibility Score (%)", "description": "Safari vs Chrome vs WebView."},
        {"id": 275, "name": "Database 'Vacuum' Success (records cleared)", "description": "History cap enforcement."},
        {"id": 276, "name": "Asset Footprint Size (MB)", "description": "App core size."},
        {"id": 277, "name": "Offline-First Resilience (hours with zero signal)", "description": "Max continuous offline usage."},
        {"id": 278, "name": "API Response Time (ms)", "description": "Price Watch engine speed."},
        {"id": 279, "name": "Conflict Frequency (per 1000 edits)", "description": "Simultaneous edits."},
        {"id": 280, "name": "QR Code Scan Speed (seconds)", "description": "In-store product identification."}
      ]
    },
    {
      "id": 9,
      "name": "User Engagement & Behavioural Analytics",
      "kpis": [
        {"id": 281, "name": "Daily Active Users (DAU)", "description": "Core engagement."},
        {"id": 282, "name": "Monthly Active Users (MAU)", "description": "Monthly reach."},
        {"id": 283, "name": "DAU/MAU Ratio (Stickiness)", "description": "How often they return."},
        {"id": 284, "name": "Average Sessions per Day", "description": "Frequency of habit."},
        {"id": 285, "name": "Average Session Duration (minutes)", "description": "Depth of engagement."},
        {"id": 286, "name": "Heatmap Hotspots (SNIS layer clicks)", "description": "Which layer used most?"},
        {"id": 287, "name": "Search Query Success Rate (%)", "description": "Finding prices."},
        {"id": 288, "name": "Null Search Results (%)", "description": "Identifying market gaps."},
        {"id": 289, "name": "Top Visited Businesses (store views)", "description": "Most popular vendors."},
        {"id": 290, "name": "Profile Progression Speed (days from Browser to Manager)", "description": "Upgrade velocity."},
        {"id": 291, "name": "User Sentiment Trend (positive/negative delta)", "description": "From PulseUpdater."},
        {"id": 292, "name": "'Coming Soon' Toast Clicks (per user)", "description": "Feature demand."},
        {"id": 293, "name": "Theme Preference (Moody vs Light %)", "description": "UI choice."},
        {"id": 294, "name": "Manual Item Creation Rate (items/user/month)", "description": "User-generated content."},
        {"id": 295, "name": "Audio Note Usage Frequency (%)", "description": "Voice vs text preference."},
        {"id": 296, "name": "WhatsApp-to-App Conversion Rate (%)", "description": "Organic growth."},
        {"id": 297, "name": "Onboarding Completion Rate (%)", "description": "First-session success."},
        {"id": 298, "name": "Help/Docs Interaction Rate (%)", "description": "System complexity."},
        {"id": 299, "name": "Churn Rate of 'Browser' Users (%)", "description": "Early drop-off."},
        {"id": 300, "name": "Self-Correction Rate (edits per user/month)", "description": "User data refinement."},
        {"id": 301, "name": "Price Alert Click-Through Rate (%)", "description": "Responsiveness to drops."},
        {"id": 302, "name": "Feature Discovery Rate (days to first Sum)", "description": "Time to advanced feature."},
        {"id": 303, "name": "User Profile Completeness (%)", "description": "Full name/number given."},
        {"id": 304, "name": "Peak Usage Hours (clock time)", "description": "Botswana shopping times."},
        {"id": 305, "name": "Multi-Device Sync Rate (%)", "description": "Phone + tablet/PC."},
        {"id": 306, "name": "In-App Navigation Depth (accordions opened)", "description": "Exploration behaviour."},
        {"id": 307, "name": "Favourited Vendor Count (avg per user)", "description": "Loyalty."},
        {"id": 308, "name": "Social Proof Impact (follows manager choice %)", "description": "Influence."},
        {"id": 309, "name": "Interaction Velocity (seconds from login to item added)", "description": "Efficiency."},
        {"id": 310, "name": "VoteWonda Engagement (polls per user/month)", "description": "Social voting."}
      ]
    },
    {
      "id": 10,
      "name": "Designer & Sourcer Economy",
      "kpis": [
        {"id": 311, "name": "Active Designer Count", "description": "Professional data curators."},
        {"id": 312, "name": "Average Note Quality Score (1-10)", "description": "Designer-curated list rating."},
        {"id": 313, "name": "Designer Listing Frequency (notes/week)", "description": "Catalog update rate."},
        {"id": 314, "name": "Average Designer Payout (Pula/month)", "description": "Earnings per curator."},
        {"id": 315, "name": "Top 5% Designer Market Share (%)", "description": "Economic concentration."},
        {"id": 316, "name": "New Farmer Sourcing Rate (farmers/designer/month)", "description": "Supply chain expansion."},
        {"id": 317, "name": "Note Accuracy Score (%)", "description": "Verified store prices vs designer claims."},
        {"id": 318, "name": "Designer Portfolio Size (active curated Notes)", "description": "Inventory breadth."},
        {"id": 319, "name": "Designer Note Cloning Rate (clones per note)", "description": "Community trust."},
        {"id": 320, "name": "Designer-to-Consumer Ratio", "description": "Market balance."},
        {"id": 321, "name": "Time to Create a 'Professional Note' (minutes)", "description": "Designer productivity."},
        {"id": 322, "name": "Designer Payout Frequency (daily vs weekly %)", "description": "Cash flow preference."},
        {"id": 323, "name": "Designer Reputation Growth (upvotes per month)", "description": "Trust."},
        {"id": 324, "name": "Impact of Designer 'Tags' on Sales (lift %)", "description": "Visibility effectiveness."},
        {"id": 325, "name": "Designer Note Update Speed (hours after price change)", "description": "Reactivity."},
        {"id": 326, "name": "Designer Multi-Category Coverage (categories/designer)", "description": "Breadth."},
        {"id": 327, "name": "Designer Geographic Spread (towns covered)", "description": "Regional coverage."},
        {"id": 328, "name": "Designer Dispute Rate (disputes per 100 notes)", "description": "Incorrect pricing claims."},
        {"id": 329, "name": "Designer Onboarding Velocity (days from signup to first commission)", "description": "Time to value."},
        {"id": 330, "name": "Designer Income Satisfaction (survey score 1-5)", "description": "Curator happiness."}
      ]
    },
    {
      "id": 11,
      "name": "Vendor & Supplier Quality",
      "kpis": [
        {"id": 331, "name": "Active Vendor Count (farmers/butchers/stores)", "description": "Supply side."},
        {"id": 332, "name": "Vendor Fulfillment Rate (%)", "description": "Orders placed vs delivered."},
        {"id": 333, "name": "Average Vendor Rating (1-5 stars)", "description": "Quality."},
        {"id": 334, "name": "Listing 'Freshness' Index (days since update)", "description": "Age of animal listing."},
        {"id": 335, "name": "Vendor Stock Accuracy (%)", "description": "#Out-of-Stock reports frequency."},
        {"id": 336, "name": "Verified Vendor Rate (%)", "description": "Businesses with validation badge."},
        {"id": 337, "name": "Supplier Loyalty Rate (repeat sales %)", "description": "Vendor retention."},
        {"id": 338, "name": "Promotional Tag Success Rate (CTR %)", "description": "#Promo tag performance."},
        {"id": 339, "name": "Vendor Store Traffic (profile views/month)", "description": "Clicks to contact/location."},
        {"id": 340, "name": "Vendor-Direct Sum Frequency (Sums from one vendor)", "description": "Single-store comparisons."},
        {"id": 341, "name": "Supplier Churn Rate (% leaving per quarter)", "description": "Vendor loss."},
        {"id": 342, "name": "Vendor Price Stability (variance over 30 days)", "description": "Frequency of hikes."},
        {"id": 343, "name": "Abattoir-to-Supplier Logistics Success (%)", "description": "Middle chain efficiency."},
        {"id": 344, "name": "Supplier Bulk-Sale Frequency (whole carcass %)", "description": "Preference for bulk."},
        {"id": 345, "name": "Vendor Platform ROI (Pula earned vs spent on tags)", "description": "Profitability for vendor."},
        {"id": 346, "name": "Average Time-to-Sale (days from listing to sold)", "description": "Inventory velocity."},
        {"id": 347, "name": "Vendor Dispute Rate (per 100 transactions)", "description": "Disagreements."},
        {"id": 348, "name": "Vendor Profile Completeness (%)", "description": "Images, descriptions."},
        {"id": 349, "name": "Vendor Subscription Renewal Rate (%)", "description": "Long-term commitment."},
        {"id": 350, "name": "Vendor Lead Quality (conversion % from click to sale)", "description": "App effectiveness."}
      ]
    },
    {
      "id": 12,
      "name": "Social Impact & Quality of Life",
      "kpis": [
        {"id": 351, "name": "Household Grocery Savings (Pula/month per family)", "description": "Direct financial impact."},
        {"id": 352, "name": "Protein Intake Frequency (meat meals/week increase)", "description": "Nutrition."},
        {"id": 353, "name": "Time Saved on Shopping Logistics (hours/user/month)", "description": "Convenience."},
        {"id": 354, "name": "Shopping Stress Reduction Score (1-10)", "description": "Peace of mind."},
        {"id": 355, "name": "Financial Literacy Growth (budget tool usage increase %)", "description": "Education."},
        {"id": 356, "name": "Social Tie Strengthening (group interactions +%)", "description": "Community cohesion."},
        {"id": 357, "name": "Female-Led Motshelo Rate (%)", "description": "Women's economic groups."},
        {"id": 358, "name": "Food Security Index (staple availability score)", "description": "Community access."},
        {"id": 359, "name": "Middle-man Markup Reduction (Pula saved by bypassing retailers)", "description": "Value to consumer."},
        {"id": 360, "name": "Crowdfunded Grocery Success Rate (%)", "description": "Bulk buying effectiveness."},
        {"id": 361, "name": "Youth Employment (active designers under 30)", "description": "Job creation."},
        {"id": 362, "name": "Meat Provenance Transparency (% of listings with farm source)", "description": "Traceability."},
        {"id": 363, "name": "Eco-Friendly Sourcing (#Grass-Fed or #Organic tags)", "description": "Sustainability."},
        {"id": 364, "name": "New Digital Wallet Adoption (users linked for first time)", "description": "Financial inclusion."},
        {"id": 365, "name": "Emergency Fund Utilization (borrows per month)", "description": "Safety net usage."},
        {"id": 366, "name": "Algorithm Fairness Score (1-10 user rating)", "description": "Trust in splits."},
        {"id": 367, "name": "Market Information Symmetry (price data access by income)", "description": "Equity."},
        {"id": 368, "name": "User Empowerment Sentiment (feeling of control)", "description": "Qualitative."},
        {"id": 369, "name": "Freshness Impact (user reports of better health)", "description": "Quality of life."},
        {"id": 370, "name": "Savings as % of Income (for bottom quintile)", "description": "Poverty reduction."},
        {"id": 371, "name": "Group Gifting/Charity Sums (donation Notes per month)", "description": "Altruism."},
        {"id": 372, "name": "Large Family Utility Rate (households 5+ using app)", "description": "Target demographic."},
        {"id": 373, "name": "Food Waste Reduction (carcass allocation %)", "description": "Efficiency."},
        {"id": 374, "name": "Digital vs Traditional Trust (app ledger preference %)", "description": "Tech adoption."},
        {"id": 375, "name": "Micro-Logistics Efficiency (neighborhood pickup success %)", "description": "Last-mile."},
        {"id": 376, "name": "Local Economy Multiplier (Pula kept in farming community)", "description": "Economic impact."},
        {"id": 377, "name": "Botho (Respect) Principle Score (sentiment analysis)", "description": "Cultural alignment."},
        {"id": 378, "name": "Local App Pride (Net Promoter Score among Batswana)", "description": "National pride."},
        {"id": 379, "name": "Meat Grading Education (knowledge test score increase)", "description": "Consumer awareness."},
        {"id": 380, "name": "Festive Savings Goal Achievement (Xmas meat funds success %)", "description": "Seasonal impact."},
        {"id": 381, "name": "Digital Herdsmen Adoption (farmers using direct sales)", "description": "Tech in agriculture."},
        {"id": 382, "name": "Price Gouging Protection (cases prevented via app data)", "description": "Consumer protection."},
        {"id": 383, "name": "Purchasing Power Stability (inflation hedge index)", "description": "Group resilience."},
        {"id": 384, "name": "Neighbourhood Cohesion (interaction frequency per 100m)", "description": "Community bonds."},
        {"id": 385, "name": "Professional Motshelo Adoption (established groups migrating)", "description": "Formalisation."},
        {"id": 386, "name": "Digital Legacy (group history persistence over 2+ years)", "description": "Long-term records."},
        {"id": 387, "name": "Intergenerational Usage (parent-child active pairs)", "description": "Family tech transfer."},
        {"id": 388, "name": "Crowdsourced Data Reliability (user price accuracy %)", "description": "Trust in peers."},
        {"id": 389, "name": "Transaction Safety (verified swaps rate)", "description": "Security."},
        {"id": 390, "name": "System Social Value (Economic + Social impact index)", "description": "Composite."},
        {"id": 391, "name": "Substitution Resilience (successful alternative find rate)", "description": "Adaptability."},
        {"id": 392, "name": "Fee Transparency Sentiment (understanding of 0.5% cut)", "description": "Trust."},
        {"id": 393, "name": "Designer Payout Consistency (variance month-to-month)", "description": "Income reliability."},
        {"id": 394, "name": "Diversity of Items (non-meat staples added per user)", "description": "Beyond protein."},
        {"id": 395, "name": "Note-to-Sum Workflow Efficiency (clicks to complete)", "description": "UI friction."},
        {"id": 396, "name": "User Privacy Satisfaction (1-10 rating)", "description": "Data firewall trust."},
        {"id": 397, "name": "Non-Tech User Onboarding (elders success rate)", "description": "Inclusive design."},
        {"id": 398, "name": "Custom Tag Innovation (unique tags per 100 users)", "description": "Creativity."},
        {"id": 399, "name": "Offline-Only Session Success (task completion without signal)", "description": "Utility."},
        {"id": 400, "name": "HistoryTracker Insights Value (relevance rating)", "description": "User perceived value."},
        {"id": 401, "name": "VoteWonda Consensus Rate (Abstain vs Yes/No ratio)", "description": "Decision quality."},
        {"id": 402, "name": "Design Minimalism Impact (cognitive load reduction score)", "description": "Simplicity."},
        {"id": 403, "name": "Resilience to Data Outages (business continuity %)", "description": "Offline robustness."},
        {"id": 404, "name": "Conflict Resolution Speed (hours from dispute to close)", "description": "PermissionsManager efficiency."},
        {"id": 405, "name": "High-Contrast Accessibility Rate (visually impaired users)", "description": "Inclusion."},
        {"id": 406, "name": "Botswana-First Branding Sentiment (cultural resonance score)", "description": "Local pride."},
        {"id": 407, "name": "Community Growth Velocity (viral coefficient)", "description": "Motshelo layer spread."},
        {"id": 408, "name": "Feature Request Conversion (% of suggestions built)", "description": "User-driven dev."},
        {"id": 409, "name": "Bothoflow Logic Loops (Item → Note → Sum → Payout cycles)", "description": "Ecosystem health."},
        {"id": 410, "name": "Namatose Success Score (weighted index of all 410 KPIs)", "description": "Overall health."}
      ]
    }
  ],
  "notes": {
    "total_kpis": "410 detailed KPIs above. To reach 500, the following 90 KPIs are provided as an extension covering cross-cutting financial and operational metrics.",
    "extension_note": "KPIs 411-500 continue from the numbering above."
  },
  "extended_kpis_411_to_500": [
    {"id": 411, "name": "Average Items per Shopping Trip (Note)", "description": "Household behaviour."},
    {"id": 412, "name": "Price Match Success Rate (Lowest price found)", "description": "Comparison value."},
    {"id": 413, "name": "Motshelo Meeting Attendance Rate (%)", "description": "Virtual vs physical."},
    {"id": 414, "name": "Group Chat Message Volume (per day)", "description": "Engagement."},
    {"id": 415, "name": "User-Reported Price Errors (per 1000 items)", "description": "Data quality."},
    {"id": 416, "name": "Average Friend Invites per User", "description": "Virality."},
    {"id": 417, "name": "Designer-User Direct Message Frequency", "description": "Relationship."},
    {"id": 418, "name": "Vendor Response Time to Inquiries (minutes)", "description": "Customer service."},
    {"id": 419, "name": "Abattoir Slaughter Capacity Utilisation (%)", "description": "Supply chain load."},
    {"id": 420, "name": "Meat Cut Customisation Requests (per month)", "description": "User demand."},
    {"id": 421, "name": "Price Drop Alert Subscriptions (per user)", "description": "Feature adoption."},
    {"id": 422, "name": "Crowdsourced Quality Photos per Item", "description": "Visual verification."},
    {"id": 423, "name": "Manager Dashboard Usage (clicks per week)", "description": "Leadership tool."},
    {"id": 424, "name": "Historical Price Lookup Frequency", "description": "Trend analysis."},
    {"id": 425, "name": "Group Savings Challenge Completion Rate", "description": "Goal setting."},
    {"id": 426, "name": "SMS Fallback Success Rate (when offline)", "description": "Resilience."},
    {"id": 427, "name": "Average Group Age vs Churn Correlation", "description": "Retention insight."},
    {"id": 428, "name": "Festive Meat Order Lead Time (days)", "description": "Planning behaviour."},
    {"id": 429, "name": "User Voice Note Length (seconds)", "description": "Audio preference."},
    {"id": 430, "name": "Image Upload Success Rate (by network)", "description": "Performance."},
    {"id": 431, "name": "Designer Note View-to-Purchase Rate", "description": "Conversion."},
    {"id": 432, "name": "Vendor Coupon Redemption Rate", "description": "Promotion."},
    {"id": 433, "name": "Neighbourhood Pickup Point Adoption", "description": "Logistics."},
    {"id": 434, "name": "Motshelo Rotation Speed (how often group buys)", "description": "Frequency."},
    {"id": 435, "name": "User Account Deletion Reason Tags", "description": "Churn analysis."},
    {"id": 436, "name": "Time Spent on Budget vs Actual Comparison", "description": "Financial mindfulness."},
    {"id": 437, "name": "In-App Customer Support Resolution Time", "description": "Service quality."},
    {"id": 438, "name": "Meat Safety Certification Check Rate", "description": "Health compliance."},
    {"id": 439, "name": "User Willingness to Prepay for Bulk Orders", "description": "Trust."},
    {"id": 440, "name": "Average Motshelo Contribution (Pula per member/month)", "description": "Economic weight."},
    {"id": 441, "name": "Price Alert to Purchase Lag (hours)", "description": "Reaction time."},
    {"id": 442, "name": "Group Disband Rate (per 100 groups/month)", "description": "Failure analysis."},
    {"id": 443, "name": "User-Added Store Locations (new vendors)", "description": "Crowdsourcing."},
    {"id": 444, "name": "Butchery Integration API Uptime (%)", "description": "Partner reliability."},
    {"id": 445, "name": "Meat Cut Local Name Usage (e.g., 'pens', 'mogodu')", "description": "Cultural relevance."},
    {"id": 446, "name": "Voice Search Query Length (words)", "description": "UX pattern."},
    {"id": 447, "name": "User Feedback on Split Fairness (monthly survey)", "description": "Botho metric."},
    {"id": 448, "name": "Average Loan Size (Pula) in Social Fund", "description": "Microcredit."},
    {"id": 449, "name": "Farmer Direct Profit Margin (%)", "description": "Value to producer."},
    {"id": 450, "name": "Weekly Active Neighbourhoods (unique areas)", "description": "Spatial growth."},
    {"id": 451, "name": "User Session Recency (days since last visit)", "description": "Engagement."},
    {"id": 452, "name": "Item Barcode Scan Rate (vs manual entry)", "description": "Efficiency."},
    {"id": 453, "name": "Motshelo Group Name Uniqueness (cultural index)", "description": "Community identity."},
    {"id": 454, "name": "Abattoir Waste Reporting (kg/month)", "description": "Sustainability."},
    {"id": 455, "name": "User Ability to Export Data (requests/month)", "description": "Data portability."},
    {"id": 456, "name": "Group Conflict Root Cause (top 3 reasons)", "description": "Resolution insight."},
    {"id": 457, "name": "Average Waiting Time for Meat Delivery (hours)", "description": "Logistics."},
    {"id": 458, "name": "User Subscription to Premium Features (%)", "description": "Revenue."},
    {"id": 459, "name": "Designer Note Translation to English/Setswana", "description": "Language support."},
    {"id": 460, "name": "Vendor Ad Spend per Acquired Customer (Pula)", "description": "Marketing ROI."},
    {"id": 461, "name": "Motshelo Group Anniversary Retention (%)", "description": "Longevity."},
    {"id": 462, "name": "User Night Mode Usage (7pm-6am)", "description": "Behaviour."},
    {"id": 463, "name": "Price Watch Alert Accuracy (price actually changed)", "description": "Algorithm."},
    {"id": 464, "name": "Community Poll Creation Rate (polls per group/month)", "description": "Democracy."},
    {"id": 465, "name": "Average Meat Share Weight Discrepancy (kg)", "description": "Trust in splitting."},
    {"id": 466, "name": "User Referral to First Purchase Time (days)", "description": "Conversion."},
    {"id": 467, "name": "Data Export for Research Requests", "description": "Academic use."},
    {"id": 468, "name": "Manager Training Completion Rate (%)", "description": "Empowerment."},
    {"id": 469, "name": "User Ability to Block/Report (frequency)", "description": "Safety."},
    {"id": 470, "name": "Motshelo Savings Interest Equivalent (Pula saved vs bank)", "description": "Value proposition."},
    {"id": 471, "name": "Seasonal Item Popularity (e.g., watermelon in summer)", "description": "Demand."},
    {"id": 472, "name": "User Login Method (Biometric vs PIN vs Password)", "description": "Security preference."},
    {"id": 473, "name": "Designer-User Dispute Resolution Time (hours)", "description": "Fairness."},
    {"id": 474, "name": "Vendor Stock Refresh Rate (listings per week)", "description": "Activeness."},
    {"id": 475, "name": "Group Member Location Concentration (within 5km %)", "description": "Proximity."},
    {"id": 476, "name": "User Emotion Tags (from voice tone analysis)", "description": "Sentiment."},
    {"id": 477, "name": "Abattoir Halal Certification Compliance Rate", "description": "Religious."},
    {"id": 478, "name": "Motshelo Contribution Reminder Open Rate (%)", "description": "Notification."},
    {"id": 479, "name": "User Cross-Visit Consistency (same items weekly)", "description": "Habit."},
    {"id": 480, "name": "Designer Note A/B Test Conversion Lift", "description": "Optimisation."},
    {"id": 481, "name": "Vendor Average Rating by Meat Type", "description": "Specialisation."},
    {"id": 482, "name": "Group Fund Disbursement Speed (hours from vote to payout)", "description": "Efficiency."},
    {"id": 483, "name": "User Offline Queue Clear Rate (pending syncs per day)", "description": "Tech."},
    {"id": 484, "name": "Neighbourhood Champion (most active user) per ward", "description": "Influence."},
    {"id": 485, "name": "Price Variance by Day of Week (weekend effect)", "description": "Market timing."},
    {"id": 486, "name": "User Ability to Handle 5MB Storage Limit (alerts triggered)", "description": "Edge case."},
    {"id": 487, "name": "Motshelo Group Photo Upload Rate (identity)", "description": "Community."},
    {"id": 488, "name": "Designer Note SEO Ranking (within app search)", "description": "Discoverability."},
    {"id": 489, "name": "Vendor Return Customer Rate (repeat buyers)", "description": "Loyalty."},
    {"id": 490, "name": "User Sentiment on Meat Quality (1-5 monthly)", "description": "Feedback."},
    {"id": 491, "name": "Abattoir-to-Consumer Distance Map (heatmap)", "description": "Logistics."},
    {"id": 492, "name": "User Financial Distress Signal (late payments)", "description": "Risk."},
    {"id": 493, "name": "Group Meeting Consensus Method (vote vs voice)", "description": "Culture."},
    {"id": 494, "name": "Price History Graph Views (per item)", "description": "Analytics."},
    {"id": 495, "name": "Designer New Category Suggestion Rate", "description": "Innovation."},
    {"id": 496, "name": "Vendor Response to Low Rating (comments)", "description": "Accountability."},
    {"id": 497, "name": "User Session Device Type (mobile vs desktop)", "description": "Platform."},
    {"id": 498, "name": "Motshelo Savings Goal Type (meat vs grain vs emergency)", "description": "Purpose."},
    {"id": 499, "name": "User Interaction with 'HistoryTracker' (clicks)", "description": "Feature."},
    {"id": 500, "name": "Namatose Holistic Impact Score (weighted 1-1000)", "description": "Ultimate metric combining all 500 KPIs."}
  ]
}